const products = [
  {
    id: 1,
    title: "for works table",
    company: "grosstech",
    image: "./img/product1.jpg",
    price: 900.99,
  },
  {
    id: 2,
    title: "home office",
    company: "crimson",
    image: "./img/product2.jpg",
    price: 790.99,
  },
  {
    id: 3,
    title: "all of needs",
    company: "worldtech",
    image: "./img/product3.jpg",
    price: 1450.99,
  },
  {
    id: 4,
    title: "security watch",
    company: "worldtech",
    image: "./img/product4.jpg",
    price: 1500.99,
  },
  {
    id: 5,
    title: "company works",
    company: "worldtech",
    image: "./img/product5.jpg",
    price: 780.99,
  },
  {
    id: 6,
    title: "personal",
    company: "aqua",
    image: "./img/product6.jpg",
    price: 690.99,
  },
  {
    id: 7,
    title: "all of needs to",
    company: "crimson",
    image: "./img/product7.jpg",
    price: 800.99,
  },
  {
    id: 8,
    title: "personal needs",
    company: "aqua",
    image: "./img/product8.jpg",
    price: 200.99,
  },
  {
    id: 9,
    title: "students",
    company: "crimson",
    image: "./img/product9.jpg",
    price: 800.95,
  },
  {
    id: 10,
    title: "engineer",
    company: "aqua",
    image: "./img/product10.jpg",
    price: 920.98,
  },
  {
    id: 11,
    title: "security",
    company: "grosstech",
    image: "./img/product11.jpg",
    price: 1000.99,
  },
  {
    id: 12,
    title: "students engineer",
    company: "grosstech",
    image: "./img/product12.jpg",
    price: 800.99,
  },
];
